import type { WorkoutTemplate, ExerciseLog, TrainingMode, EngineAdjustmentResult } from './types';
import type { FitnessGoal } from '../types';

export const PROGRESSION_CASUAL_INCREASE_PERCENT = 0.025; // +2.5%

/**
 * The Epley Formula for Estimated One-Rep Max (e1RM)
 */
export function calculateE1RM(weight: number, reps: number): number {
  if (reps === 0) return 0;
  if (reps === 1) return weight;
  return weight * (1 + reps / 30);
}

/**
 * Strength Retention Monitor
 * 
 * Logic: Compare recent 3 sessions avg e1RM vs prior 3 sessions avg e1RM.
 * Trigger if recent < 90% of prior AND user is in a caloric deficit.
 */
export function checkStrengthRetention(
  exerciseId: string,
  workoutHistory: ExerciseLog[],
  isNutritionDeficit: boolean
): boolean {
  // Filter history for this specific exercise
  const logs = workoutHistory
    .filter(log => log.exercise_id === exerciseId)
    .sort((a, b) => new Date(b.performed_at).getTime() - new Date(a.performed_at).getTime());

  if (logs.length < 6) return false; // Need at least 6 sessions to compare 3 vs 3

  const recentAvg = logs.slice(0, 3).reduce((acc, log) => acc + calculateE1RM(log.weight, log.reps), 0) / 3;
  const priorAvg = logs.slice(3, 6).reduce((acc, log) => acc + calculateE1RM(log.weight, log.reps), 0) / 3;

  if (priorAvg === 0) return false;

  const retentionRatio = recentAvg / priorAvg;

  return retentionRatio < 0.9 && isNutritionDeficit;
}

/**
 * Adjusts a generated workout template based on previous performance data.
 * 
 * @param template Base workout generated by the AI
 * @param performanceHistory A full history of the user's logged exercises
 * @param trainingMode 'casual' or 'serious'
 * @returns The adjusted workout template and a list of applied adjustments
 */
export function adjustProgram(
  template: WorkoutTemplate,
  performanceHistory: ExerciseLog[],
  trainingMode: TrainingMode = 'casual',
  goal: FitnessGoal = 'maintenance'
): EngineAdjustmentResult {
  const adjustmentsMade: string[] = [];
  
  const adjustedSlots = template.slots.map(slot => {
    const adjustedEntries = slot.entries.map(entry => {
      // Find the most recent log for this specific exercise
      const recentLogs = performanceHistory
        .filter(log => log.exercise_id === entry.name) // Engine usually matches by name for template flexibility
        .sort((a, b) => new Date(b.performed_at).getTime() - new Date(a.performed_at).getTime());

      const lastLog = recentLogs[0];
      
      let targetWeight = entry.targetWeight;
      let targetSets = entry.targetSets;
      let targetReps = entry.targetReps;
      let restTimeSec = 90;

      if (goal === 'fat_loss') {
        targetSets = 3;
        targetReps = "10-15";
        restTimeSec = 60;
      } else if (goal === 'muscle_gain') {
        targetSets = 4;
        targetReps = "8-12";
        restTimeSec = 90;
      } else if (goal === 'strength') {
        targetSets = 5;
        targetReps = "3-5";
        restTimeSec = 180;
      }

      if (lastLog) {
        if (trainingMode === 'casual') {
          const newWeight = parseFloat((lastLog.weight * (1 + PROGRESSION_CASUAL_INCREASE_PERCENT)).toFixed(2));
          targetWeight = newWeight;
          adjustmentsMade.push(`Increased weight for ${entry.name} by 2.5% based on previous completion.`);
        } else if (trainingMode === 'serious') {
          const loggedRpe = lastLog.rpe || 8;
          let increasePercent = 0;
          let rpeTarget = 8;

          if (loggedRpe < 7) {
            increasePercent = 0.05;
            rpeTarget = Math.min(10, loggedRpe + 2);
            adjustmentsMade.push(`Increased weight for ${entry.name} by 5% due to low RPE (${loggedRpe}). Target RPE ${rpeTarget}.`);
          } else if (loggedRpe >= 7 && loggedRpe < 9) {
            increasePercent = 0.025;
            rpeTarget = loggedRpe;
            adjustmentsMade.push(`Increased weight for ${entry.name} by 2.5% based on RPE ${loggedRpe}. Target RPE ${rpeTarget}.`);
          } else {
            increasePercent = 0;
            rpeTarget = 8;
            adjustmentsMade.push(`Maintained weight for ${entry.name} due to high RPE (${loggedRpe}). Target RPE ${rpeTarget}.`);
          }

          const newWeight = parseFloat((lastLog.weight * (1 + increasePercent)).toFixed(2));
          targetWeight = newWeight;
          entry.rpeTarget = rpeTarget;
        }
      }

      return {
        ...entry,
        targetWeight,
        targetSets,
        targetReps,
        restTimeSec,
      };
    });

    return {
      ...slot,
      entries: adjustedEntries
    };
  });

  return {
    adjustedTemplate: {
      ...template,
      slots: adjustedSlots
    },
    adjustmentsMade
  };
}
