import type { WorkoutTemplate, ExerciseLog, TrainingMode, EngineAdjustmentResult } from './types';

export const PROGRESSION_CASUAL_INCREASE_PERCENT = 0.025; // +2.5%

/**
 * Adjusts a generated workout template based on previous performance data.
 * 
 * @param template Base workout generated by the AI
 * @param performanceHistory A full history of the user's logged exercises
 * @param trainingMode 'casual' or 'serious'
 * @returns The adjusted workout template and a list of applied adjustments
 */
export function adjustProgram(
  template: WorkoutTemplate,
  performanceHistory: ExerciseLog[],
  trainingMode: TrainingMode = 'casual'
): EngineAdjustmentResult {
  const adjustmentsMade: string[] = [];
  
  const adjustedExercises = template.exercises.map(exercise => {
    // Find the most recent log for this specific exercise
    const recentLogs = performanceHistory
      .filter(log => log.exercise_id === exercise.id)
      .sort((a, b) => new Date(b.performed_at).getTime() - new Date(a.performed_at).getTime());

    const lastLog = recentLogs[0];
    
    // Default fallback to keep original template stats
    let targetWeight = exercise.targetWeight;
    let targetSets = exercise.targetSets;
    // We keep targetReps as string "8-12" from AI, could be parsed later if needed.

    if (lastLog) {
      if (trainingMode === 'casual') {
        // Simple +2.5% progression
        const newWeight = parseFloat((lastLog.weight * (1 + PROGRESSION_CASUAL_INCREASE_PERCENT)).toFixed(2));
        targetWeight = newWeight;
        adjustmentsMade.push(`Increased weight for ${exercise.name} by 2.5% based on previous completion.`);
      } else if (trainingMode === 'serious') {
        // v1.2 RPE based adjustments
        const loggedRpe = lastLog.rpe || 8; // Default to 8 if no RPE was logged
        let increasePercent = 0;
        let rpeTarget = 8;

        if (loggedRpe < 7) {
          increasePercent = 0.05; // 5% increase for low exertion
          rpeTarget = Math.min(10, loggedRpe + 2); // Push them harder
          adjustmentsMade.push(`Increased weight for ${exercise.name} by 5% due to low RPE (${loggedRpe}). Target RPE ${rpeTarget}.`);
        } else if (loggedRpe >= 7 && loggedRpe < 9) {
          increasePercent = 0.025; // 2.5% increase for optimal RPE
          rpeTarget = loggedRpe; // Aim to maintain same feeling
          adjustmentsMade.push(`Increased weight for ${exercise.name} by 2.5% based on RPE ${loggedRpe}. Target RPE ${rpeTarget}.`);
        } else {
          // RPE 9-10 (High Exertion)
          increasePercent = 0; // Maintain weight to allow recovery / adaptation
          rpeTarget = 8; // Goal is to hit 8 next time with the same weight
          adjustmentsMade.push(`Maintained weight for ${exercise.name} due to high RPE (${loggedRpe}). Target RPE ${rpeTarget}.`);
        }

        const newWeight = parseFloat((lastLog.weight * (1 + increasePercent)).toFixed(2));
        targetWeight = newWeight;
        exercise.rpeTarget = rpeTarget;
      }
    }

    return {
      ...exercise,
      targetWeight,
      targetSets,
    };
  });

  return {
    adjustedTemplate: {
      ...template,
      exercises: adjustedExercises
    },
    adjustmentsMade
  };
}
